version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  mongo-primary:
    image: bitnami/mongodb:latest
    environment: 
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD=nitro123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=nitro
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=kartoffel
    ports:
      - 27017:27017
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  monstache:
    image: rwynn/monstache:rel6
    command: -f ./config.toml
    working_dir: /app
    depends_on: 
      - mongo-primary
      - elasticsearch
    volumes:
      - ./docker-compose-config/monstache/config/config.toml:/app/config.toml
      - ./docker-compose-config/monstache/config/scripts:/app/scripts
  kartoffel:
    build:
      context: .
      dockerfile: Dockerfile-kartoffel
    container_name: kartoffel
    image: "davidhey/kartoffel"
    depends_on: 
      - mongo-primary
      - elasticsearch
      - redis
    ports:
      - "3000:3000"
  mockserver:
    build:
      context: .
      dockerfile: Dockerfile-mockServer
    container_name: mockserver
    image: "davidhey/mockserver"
    ports:
      - "3001:3001"
  
