mongo-url = "mongodb://nitro:password123@mongo-primary:27017,mongo-secondary:27017/kartoffel?replicaSet=rs0"
elasticsearch-urls = ["http://elasticsearch:9200"]
verbose = true

change-stream-namespaces = ["kartoffel.people"]

direct-read-namespaces = ["kartoffel.people"]

elasticsearch-retry = true

enable-http-server= true

# workers = ["w1", "w2"]
# cluster-name = "HA"

# replay = true
resume = true

stats= true

[logs]
error = "logs/error.log"

[[script]]
namespace = "kartoffel.organizationgroups"
path = "scripts/transform_group.js"

[[script]]
namespace = "kartoffel.people"
path = "scripts/transform_person.js"

[[script]]
path = "scripts/filter_fields.js"
